### ISSUE TITLE
Don't WORK.

### ISSUE THREAD

**Issue by Master-Antonio** [amargon/nodebb-plugin-discord-notification#1]
The plugin don't work.
I noticed that the id of Webhook change after that i saved.
From 309086633595109377 to 309086633595109400.

**Comment by amargon** [comment]
Well, that’s strange…

Webhook ID changes, when the plugin settings page loads:

XXXXXXXXXXXXXXX144 –> XXXXXXXXXXXXXXX140
XXXXXXXXXXXXXXX377 –> XXXXXXXXXXXXXXX400

but there is nothing in my code that rounds numbers.
More to say, Webhook ID field type is «text»! :)

P.S. As for now the workaround is to re-paste Webhook ID when you change other plugin settings.

**Comment by Master-Antonio** [comment]
Can you tell me the file in question and the name of the variable.

**Comment by Master-Antonio** [comment]
Try to use a "int" and after cast in "string".

**Comment by amargon** [comment]
I wonder what reason NodeBB Slack plugin author had to define [all plugin settings as strings](https://github.com/amargon/nodebb-plugin-discord-notification/blob/9ce72176defe54fa1582958fe82d5310e272969b/library.js#L16)

Perhaps it’s just very old Settings API and I shouldn't have touched it :)

I’ll re-check the NodeBB Plugins docs first.

**Comment by amargon** [comment]
It turns out that [NodeBB settings module converts Webhook ID to actual number and rounds it](https://github.com/NodeBB/NodeBB/issues/5645) 😄

The only workaround I can think of is to parse full webhook URL instead of having separate ID and Token fields.

**Comment by amargon** [comment]
OK, now plugin parses full webhook URL, so webhook ID stays safe.

Since I could not find an example on how to update plugin data structure in DB, you have to purge old settings manually: `db.objects.remove({_key: "settings:discord-notification"});`
