### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by tylerstraub** [amargon/nodebb-plugin-discord-notification#3]
Configured exactly as specified in the Readme, though it's not pushing anything to the Discord server. Nothing in the NodeBB log output to go off of either. Any suggestions? 

Thank you!

**Comment by amargon** [comment]
Oh, please check the latest version!
I forgot to push an update for NodeBB 1.5.x.

I still can’t get used to the fact that someone other than me uses this plugin :)

**Comment by tylerstraub** [comment]
Awesome thank you so much Amargon, I will report back later today on my status. This plugin is such a great idea I am surprised that you don't have a lot more users. Now if there was only a working SSO branch for NodeBB =P Cheers!

**Comment by tylerstraub** [comment]
I just now noticed that I'm receiving some missing deps errors while trying to npm install.

`npm WARN discord.js@11.1.0 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.1.0 requires a peer of node-opus@^0.2.5 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of libsodium-wrappers@^0.5.1 but none was installed.`

Also having trouble with building all of these peer modules properly. Perhaps I need to clear the node_modules and do a complete re-installation?

**Comment by amargon** [comment]
Discord.js package is a full-featured Discord API client, and that means voice support, etc. But when it comes to simple webhook notifications it should work fine even without these optional modules.

I don't have them installed :)

**Comment by tylerstraub** [comment]
It looks like I also had some other corruption going on with my NodeBB installation in general. After a complete instance refresh and re-installation of the module everything worked perfectly. Really excited to put this to use, thank you again for the support. Great tool!
