### ISSUE TITLE
Invalid Form Body

### ISSUE THREAD

**Issue by Yann151924** [amargon/nodebb-plugin-discord-notification#4]
I got this error : 
```{ DiscordAPIError: Invalid Form Body
embeds[0].footer.icon_url: Not a well formed URL.
    at DiscordAPIError (/home/http/forum/node_modules/discord.js/src/client/rest/DiscordAPIError.js:6:5)
    at item.request.gen.end (/home/http/forum/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/http/forum/node_modules/snekfetch/src/index.js:241:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'DiscordAPIError',
  message: 'Invalid Form Body\nembeds[0].footer.icon_url: Not a well formed URL.',
  code: 50035 }
```

**Comment by amargon** [comment]
It should be fine now in v1.3.1.

**Comment by Yann151924** [comment]
Not fix i have the same error :( , if it can help i use the gravatar with custom default image, that could be the problem

**Comment by amargon** [comment]
Hmm... I could not reproduce the problem on my NodeBB test bed.
How does your custom image URL look like?

**Comment by Yann151924** [comment]
My custom image url is : `https://minotar.net/bust/%user/100.png`

**Comment by amargon** [comment]
Still can’t reproduce the issue:

![Gravatar Test](https://user-images.githubusercontent.com/25489446/27426516-a461d194-5744-11e7-9797-8dd8d0db5499.png)

Are you sure you’ve updated the plugin to the latest version?

P.S. If your NodeBB is older than 1.5.x, you’ll have to change [this line](https://github.com/amargon/nodebb-plugin-discord-notification/blob/v1.2.0/library.js#L76) to [this one](https://github.com/amargon/nodebb-plugin-discord-notification/blob/v1.3.1/library.js#L78) to apply the fix manually.

**Comment by Yann151924** [comment]
So it's working now :D , so my apologies :).
