### ISSUE TITLE
Mention @everyone or @here

### ISSUE THREAD

**Issue by Yann151924** [amargon/nodebb-plugin-discord-notification#5]
Can you think it's possible to add an option in admin control panel to mention @everyone or other mention when the webhook is used ?

i will put a pr for this i think :)

**Comment by Yann151924** [comment]
Pull request #6

**Comment by amargon** [comment]
I bet if we implement this, the next ticket would be about custom mentions (members or roles) :)

So it’s better to add this option right away. Say, as a «Mentions» section with a dropdown list — `None / @here / @everyone / Custom...` …Or maybe just a simple «Message content» text field.

Any combination of mentions could be passed as a message content (`@everyone`, `@here`, even `<@!UserID>` or `<@&RoleID>`).

**Comment by Yann151924** [comment]
Simple "Message content" can do the job i think. Any user can add custom text and mention.

**Comment by Yann151924** [comment]
I made the modification in the pr, it's normally work :)

**Comment by amargon** [comment]
I hope you don’t mind that I modified the PR to save us some time :)
I’ll update the docs a bit later and then the new version would be ready to go.

**Comment by Yann151924** [comment]
No prob :)
