### ISSUE TITLE
Plugin is crashing NodeBB

### ISSUE THREAD

**Issue by jdutriaux** [amargon/nodebb-plugin-discord-notification#7]
Hello, I have installed your plugin on my nodeBB board but it crashes the NodeBB process with this error : 

```
error:  SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /data/www/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:72:27
    at /data/www/nodebb/node_modules/async/dist/async.js:3861:9
    at /data/www/nodebb/node_modules/async/dist/async.js:421:16
    at iterateeCallback (/data/www/nodebb/node_modules/async/dist/async.js:928:24)
    at /data/www/nodebb/node_modules/async/dist/async.js:906:16
    at /data/www/nodebb/node_modules/async/dist/async.js:3858:13
    at /data/www/nodebb/src/database/redis/hash.js:50:4
    at Multi.callback (/data/www/nodebb/src/database/redis/hash.js:79:4)
    at multi_callback (/data/www/nodebb/node_modules/redis/lib/multi.js:89:14)
    at Command.callback (/data/www/nodebb/node_modules/redis/lib/multi.js:116:9)
    at normal_reply (/data/www/nodebb/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/data/www/nodebb/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/data/www/nodebb/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/data/www/nodebb/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/data/www/nodebb/node_modules/redis/index.js:274:27)
```

I'm on v1.7.0 of NodeBB.

Thanks for your help :smile:.

**Comment by amargon** [comment]
Oh my, there is something really wrong with notifications on GitHub…

Does it still crash your forum?

**Comment by 4m2c4bl3** [comment]
it's still happening - it crashes if you don't have the webhook url filled in.

**Comment by nefarius** [comment]
Still happening 😬

**Comment by ghost** [comment]
I have this issue and am disappointed to see that this issue has been open for _three years_. ☹

**Comment by ghost** [comment]
> it's still happening - it crashes if you don't have the webhook url filled in.

How am I supposed to set the webhook URL if I can't get to the plugin's config page?

**Comment by ghost** [comment]
hmm in my case here is the error when I try to load the config
```
(node:2126541) UnhandledPromiseRejectionWarning: Error: Failed to lookup view "admin/plugins/discord-notification" in views directory "/srv/NodeBB/build/public/templates"
    at Function.render (/srv/NodeBB/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/srv/NodeBB/node_modules/express/lib/response.js:1012:7)
    at /srv/NodeBB/src/middleware/render.js:89:11
    at new Promise (<anonymous>)
    at renderContent (/srv/NodeBB/src/middleware/render.js:88:10)
    at ServerResponse.renderOverride [as render] (/srv/NodeBB/src/middleware/render.js:64:14)
```

**Comment by amargon** [comment]
> I have this issue and am disappointed to see that this issue has been open for _three years_. ☹

@ledlamp, ah, and I'm quite disappointed that during these three years no one has mentioned even a tiny detail about their environments: you know, NodeBB version, nodejs version, etc.

I just can't fix the issue I can't reproduce — even if I happen to have some time to spare for that project.

**Comment by ghost** [comment]
> > I have this issue and am disappointed to see that this issue has been open for _three years_. ☹
> 
> @ledlamp, ah, and I'm quite disappointed that during these three years no one has mentioned even a tiny detail about their environments: you know, NodeBB version, nodejs version, etc.
> 
> I just can't fix the issue I can't reproduce — even if I happen to have some time to spare for that project.

Why didn't you ask them then? The original post said v1.7.0. I'm using v1.15.2 on node 14.15.0 on centos 8.

**Comment by nefarius** [comment]
@amargon I'll spin up a new recent installation, install it and dump everything I can find here, maybe it helps. Am unfortunately not deep into Node myself so all I can provide is logs and the info you said you needed.

Cheers

**Comment by nefarius** [comment]
Uh, this is really odd, just installed the latest plugin (1.5.0) on latest NodeBB stable (v1.15.2) and it works as designed...

![image](https://user-images.githubusercontent.com/286631/99982147-868cd980-2daa-11eb-9d54-3e1257494a2b.png)

![image](https://user-images.githubusercontent.com/286631/99982178-8c82ba80-2daa-11eb-98b9-68cd1b0217cf.png)

Webhook fired as well:

![image](https://user-images.githubusercontent.com/286631/99982580-0a46c600-2dab-11eb-9d5b-6c4bc9165118.png)

So yeah... computers 😅

**Comment by amargon** [comment]
> Why didn't you ask them then?

Why should I? We're not in class, I'm not anyone's teacher of GitHub basics, and I've got plenty of other work to do.
Besides, it's quite obvious that no one can just guess how someone else's forum is set up.

> I'll spin up a new recent installation, install it and dump everything I can find here

@nefarius, ah, I was going to do the same next weekend, but

>  it works as designed...

😄

**Comment by nefarius** [comment]
Sorry for the noise... I changed a lot since I last tried to "fix" this plugin, but it seems now with the [new shiny Docker image](https://github.com/rez0n/docker-nodebb) I use all these weird issues are a thing of the past 👍

**Comment by amargon** [comment]
@nefarius well, the plugin itself is not that complex to make NodeBB crash because of it (the worst case I've seen was а webhook not firing because of missing user avatar), but those little details of compatibility between specific NodeBB version, nodejs version, other plugins, etc, can be a real headache.
