### ISSUE TITLE
Is this still supposed to work?

### ISSUE THREAD

**Issue by nefarius** [amargon/nodebb-plugin-discord-notification#9]
Heya!

I was just trying to set up this plugin in a fresh docker'ized environment of NodeBB v1.10.1 and after the plugin installation & restart in the logs I get:

```shell
Missing translation "discord-notification:title"
2018-09-10T20:44:11.844Z [22] - error: /assets/templates/admin/plugins/discord-notification.js
 Error: ENOENT: no such file or directory, open '/usr/src/nodebb/build/public/templates/admin/plugins/discord-notification.tpl'
```

Admin panel simply freezes while the Browser console spits this out:

![image](https://user-images.githubusercontent.com/286631/45323453-66ff9280-b54b-11e8-80e4-4abb4ac1c8cc.png)

That's not supposed to look like that as well I guess:

![image](https://user-images.githubusercontent.com/286631/45323527-b1810f00-b54b-11e8-80d3-3be5c1e2394a.png)

If you need more info, I can provide 🙂 

Thanks!

**Comment by nefarius** [comment]
It works now! I had to manually copy these two missing files into the container:

```shell
wget "https://raw.githubusercontent.com/amargon/nodebb-plugin-discord-notification/master/languages/en-GB/discord-notification.json" -P /usr/src/nodebb/build/public/language/en-GB
wget "https://raw.githubusercontent.com/amargon/nodebb-plugin-discord-notification/master/public/templates/admin/plugins/discord-notification.tpl" -P /usr/src/nodebb/build/public/templates/admin/plugins
```

Now I just need to find out if I can also fix the broken special chars and avatar in the payload as well:

![image](https://user-images.githubusercontent.com/286631/45326043-e3e23a80-b552-11e8-93fb-71d810f40a38.png)

**Update:** pardon the spam, the Avatar is my fault, the Discord servers can't access the avatar image while the Webserver is firewall'ed during maintenance 💩

**Comment by ghost** [comment]
I wonder why they were missing
